module.exports = {
	'coven': require('./coven'),
	'divine': require('./divine'),
	'rvt': require('./rvt'),
	'dalston-superstore': require('./dalston-superstore'),
	'fire': require('./fire'),
	'lightbox': require('./lightbox'),
	'two-brewers': require('./two-brewers'),
	'heaven': require('./heaven'),
	'xoyo': require('./xoyo'),
	'bgwmc': require('./bgwmc'),
	'eagle': require('./eagle'),
	'white-swan': require('./white-swan'),
	'comptons': require('./comptons'),
	'duke-of-wellington': require('./duke-of-wellington'),
	'bar-soho': require('./bar-soho'),
	'halfway-to-heaven': require('./halfway-to-heaven'),
	'freedom': require('./freedom'),
	'howl': require('./howl'),
	'sextou': require('./sextou'),
	'tech-couture': require('./tech-couture'),
	'smut': require('./smut'),
	'fold': require('./fold'),
	'maiden-voyage': require('./maiden-voyage'),
	'body-movements': require('./body-movements'),
	'club-are': require('./club-are'),
};
